apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aksdemozaaliv22
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aksdemozaali-kub-app22
    spec:
      containers:
        - name: aksdemozaali-services-app22
          image: aksdemozaali.azurecr.io/aksnet:v12
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: aksdemozaali-kub-app22
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - name: http-port
      port: 80
      targetPort: 80
  selector:
    app: aksdemozaali-kub-app22